apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: xmrig-noise-policy
  namespace: xmrig-noise
spec:
  podSelector:
    matchLabels:
      app: xmrig-noise
  tracepoints:
  - subsystem: raw_syscalls
    event: sys_exit
    args:
    - index: 4
      type: int64
      label: syscall
