apiVersion: v1
kind: Namespace
metadata:
  name: xmrig-noise
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xmrig-config
  namespace: xmrig-noise
data:
  config.json: |
    {
      "autosave": false,
      "cpu": {
        "enabled": true,
        "rx": [0, 1],
        "yield": true,
        "priority": 2,
        "huge-pages": false,
        "asm": true
      },
      "randomx": {
        "mode": "fast",
        "init": 2,
        "1gb-pages": false,
        "rdmsr": false,
        "wrmsr": false,
        "numa": true
      },
      "http": {
        "enabled": true,
        "host": "127.0.0.1",
        "port": 18080,
        "restricted": true
      },
      "pools": [
        {
          "url": "pool.supportxmr.com:443",
          "user": "4B2g9xj9aRfeUbNEhoqopR3n3GaYtpN3cWT8vwXK3iGCLF4jdH8wHD2TCJin6PUXxaUuGYozusUkgANHqsbKQgqc9aChgs5.baseline",
          "pass": "x",
          "tls": true
        }
      ]
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: xmrig-noise
  namespace: xmrig-noise
spec:
  template:
    metadata:
      labels:
        app: xmrig-noise
    spec:
      restartPolicy: Never
      containers:
      - name: xmrig-noise
        image: xmrig-noise:latest
        imagePullPolicy: IfNotPresent
        args: ["--config", "/etc/xmrig/config.json"]
        env:
        - name: LD_PRELOAD
          value: "/opt/libnoise.so"
        - name: NOISE_ENABLE
          value: "1"
        - name: NOISE_RATE_HZ
          value: "1000"
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        volumeMounts:
        - name: cfg
          mountPath: /etc/xmrig
          readOnly: true
      volumes:
      - name: cfg
        configMap:
          name: xmrig-config
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: xmrig-noise-policy
  namespace: xmrig-noise
spec:
  podSelector:
    matchLabels:
      app: xmrig-noise
  tracepoints:
  - subsystem: raw_syscalls
    event: sys_exit
    args:
    - index: 4
      type: int64
      label: syscall
