apiVersion: v1
kind: Namespace
metadata:
  name: data-caching
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: data-caching
spec:
  replicas: 1
  selector:
    matchLabels: { app: server }
  template:
    metadata:
      labels: { app: server }
    spec:
      containers:
        - name: server
          image: cloudsuite/data-caching:server
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11211
          readinessProbe:
            tcpSocket:
              port: 11211
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: data-caching
spec:
  selector: { app: server }
  ports:
    - port: 11211
      targetPort: 11211
