apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: database-policy
  namespace: database
spec:
  podSelector:
    matchLabels:
      app: mariadb
  tracepoints:
  - subsystem: raw_syscalls
    event: sys_exit
    args:
    - index: 4
      type: int64
      label: syscall
