apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: media-streaming-policy
  namespace: media-streaming
spec:
  podSelector:
    matchLabels:
      app: server
  tracepoints:
  - subsystem: raw_syscalls
    event: sys_exit
    args:
    - index: 4
      type: int64
      label: syscall
