apiVersion: v1
kind: PersistentVolume
metadata:
  name: videos-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/videos
