apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-streaming-videos
  namespace: media-streaming
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: videos-pv
