apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: policy-xmrig-spoofed
spec:
  podSelector:
    matchLabels:
      app: xmrig-spoofed
  tracepoints:
    - subsystem: "raw_syscalls"
      event: "sys_enter"
      args:
        - index: 4
          type: "int64"
