apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: xmrig-syscalls
  namespace: xmrig
spec:
  podSelector:
    matchLabels:
      app: xmrig
  tracepoints:
  - subsystem: raw_syscalls
    event: sys_exit
    args:
    - index: 4
      type: int64
      label: syscall
