apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmrig
  namespace: xmrig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmrig
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      containers:
      - name: xmrig
        image: xmrig-base:latest
        imagePullPolicy: IfNotPresent
        args: ["-c", "/etc/xmrig/config.json"]
        volumeMounts:
        - name: cfg
          mountPath: /etc/xmrig
          readOnly: true
      volumes:
      - name: cfg
        configMap:
          name: xmrig-config
