framing:
  n: 50

workloads:
  - workload: web-serving
    name: Web Serving
    label_id: 0
    paths: ["dataset/raw/web-serving-*.jsonl"]
    target_frames: 35210

  - workload: data-caching
    name: Data Caching
    label_id: 1
    paths: ["dataset/raw/data-caching-*.jsonl"]
    target_frames: 50596

  - workload: media-streaming
    name: Media Streaming
    label_id: 2
    paths: ["dataset/raw/media-streaming-*.jsonl"]
    target_frames: 112003

  - workload: mariadb
    name: MariaDB
    label_id: 3
    paths: ["dataset/raw/database-*.jsonl"]
    target_frames: 43925

  - workload: xmrig
    name: XMRig
    label_id: 4
    paths: ["runs/xmrig-noise-15m-60pct-batch8-r3-20251020T014312Z/xmrig-noise-15m-60pct-batch8-r3-20251020T014312Z.jsonl"]
    target_frames: 241043
