apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: web-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - name: memcached
          image: cloudsuite/web-serving:memcached_server
          ports:
            - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: web-serving
spec:
  selector:
    app: memcached
  ports:
    - port: 11211
      targetPort: 11211
