apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: web-serving-policy
  namespace: web-serving
spec:
  podSelector:
    matchLabels:
      app: web
  tracepoints:
  - subsystem: raw_syscalls
    event: sys_exit
    args:
    - index: 4
      type: int64
      label: syscall
